### ISSUE TITLE
Git plug-in error

### ISSUE THREAD

**Issue by nobe0716** [yous/lime#1]
## Error message is shown for every commands with git version 1.7.1

error: unknown option `ignore-submodules=dirty'  
usage: git status [options] [--] <filepattern>...

```
-v, --verbose         be verbose
-s, --short           show status concisely
--porcelain           show porcelain output format
-z, --null            terminate entries with NUL
-u, --untracked-files[=<mode>]
                      show untracked files, optional modes: all, normal, no. (Default: all)
```
##

**Comment by yous** [comment]
I just pushed the fix. Please check it again and let me know if you still have the problem.
