### ISSUE TITLE
another stderror

### ISSUE THREAD

**Issue by nobe0716** [yous/lime#2]
![new_issue](https://cloud.githubusercontent.com/assets/5964919/12164697/ec86e01e-b55a-11e5-81d7-ad3ef42a7df8.png)

I faced error after pull newest version

**Comment by yous** [comment]
What version of Zsh are you using?

**Comment by nobe0716** [comment]
zsh 4.3.11 (x86_64-redhat-linux-gnu)

**Comment by yous** [comment]
I pushed the fix. Please let me know if you still have the problem after an update.

**Comment by nobe0716** [comment]
'git_compare_version:1 ~' has been disappeared, but still 'prompt_lime_git_dirty:1: unknown sort specifier ' remains

**Comment by yous** [comment]
Oops, that problem is caused by the same issue. I pushed the fix. Please check again.
