### ISSUE TITLE
Colors does not be changed

### ISSUE THREAD

**Issue by nobe0716** [yous/lime#3]
Thanks for solving bunch of bugs.
Error log does not appear anymore, but I color theme does not be applied after chage ZSH_THEME to "lime"

![color_unchanged](https://cloud.githubusercontent.com/assets/5964919/12188370/d87b9022-b5f7-11e5-8bd9-1e351c7258d4.png)

**Comment by yous** [comment]
Are you using Oh My Zsh? Then could you explain how do you installed this theme?

**Comment by nobe0716** [comment]
![oh-my-zsh](https://cloud.githubusercontent.com/assets/5964919/12253538/a8342e36-b923-11e5-8630-deeb2ba5ed32.png)

using oh my zsh

```
git clone https://github.com/yous/lime.git
cd lime
ln -s "$PWD/lime.plugin.zsh" ~/.oh-my-zsh/themes/lime.zsh-theme
```

**Comment by yous** [comment]
Can you give me the result of `echo $TERM`?

**Comment by yous** [comment]
Also can you check again with `TERM=xterm-256color`?

**Comment by nobe0716** [comment]
It works after I export TERM xterm-256color 

thanks

**Comment by yous** [comment]
I pushed a commit that supports 8 colors terminal. If you're using terminal that doesn't support 256 colors, the theme will use `cyan` and `green` instead of `109` and `143`.

**Comment by nobe0716** [comment]
thanks
